<?php

function triangle_menu() {
  $items = array();

  $items['triangle_tracker'] = array(
      'title' => 'Triangle Tracker',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('triangle_tracker_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['triangle_tracker_success_page'] = array(
      'title' => 'Success',
      'page callback' => 'triangle_tracker_success',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function triangle_tracker_form() {
  $form['side_one'] = array(
    '#title' => 'Side one',
    '#description' => 'Enter the first side of the triangle',
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );

  $form['side_two'] = array(
    '#title' => 'Side two',
    '#description' => 'Enter the second side of the triangle',
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );

  $form['side_three'] = array(
    '#title' => 'Side three',
    '#description' => 'Enter the third side of the triangle',
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#value' => 'Go!',
    '#type' => 'submit',
  );
  return $form;
}

function triangle_tracker_form_validate($form, &$form_state) {
    $a = $form_state['values']['side_one'];
    $b = $form_state['values']['side_two'];
    $c = $form_state['values']['side_three'];

    if(($a + $b) < $c) {
        form_set_error('side_one', 'This is not a triangle, please try again.');
        form_set_error('side_two');
        form_set_error('side_three');
    } elseif (($c + $b) < $a) {
        form_set_error('side_one', 'This is not a triangle, please try again.');
        form_set_error('side_two');
        form_set_error('side_three');
    } elseif (($c + $a) < $b) {
        form_set_error('side_one', 'This is not a triangle, please try again.');
        form_set_error('side_two');
        form_set_error('side_three');
    }
}

function triangle_tracker_form_submit($form, &$form_state) {
  $a = $form_state['values']['side_one'];
  $b = $form_state['values']['side_two'];
  $c = $form_state['values']['side_three'];
  if ( (($a * $a) + ($b * $b) === ($c * $c)) || (($b * $b) + ($c * $c) === ($a * $a)) || (($c * $c) + ($a * $a) === ($b * $b)) ) {
    $output =  'This is a right triangle. Congrats!';
  } else if ($a === $b && $b === $c && $a===$c) {
    $output = 'This is an equilateral triangle. Woohoo!';
  } else if ( ($a === $b) || ($a === $c) || ($c === $b) ) {
    $output = 'This is an isoceles triangle. Good work!';
  } else {
    $output = 'This is a scalene triangle. Odd.';
  }
  $_SESSION['triangle_result'] = $output;
  $form_state['redirect'] = 'triangle_tracker_success_page';
}

function triangle_tracker_success() {
  return $_SESSION['triangle_result'];
}
