<?php

 function shift_cipher_menu() {
     $items['shift_cipher'] = array(
         'title' => 'Shift Cipher',
         'access callback' => TRUE,
         'page callback' => 'drupal_get_form',
         'page arguments' => array('shift_cipher_form'),
         'type' => MENU_NORMAL_ITEM,
     );
     $items['shift_cipher_results_page'] = array(
         'title' => 'Shift Cipher Results',
         'access callback' => TRUE,
         'page callback' => 'shift_cipher_results',
         'type' => MENU_CALLBACK,
     );
     return $items;
 }


//Shift Cipher Form
 function shift_cipher_form() {
     $form['shift_value'] = array(
         '#title' => 'Shift value',
         '#type' => 'textfield',
         '#description' => 'Enter a positive integer.',
         '#required' => TRUE,
         '#element_validate' => array('element_validate_integer_positive'),
     );
     $form['shift_direction'] = array(
         '#title' => 'Shift direction',
         '#type' => 'textfield',
         '#description' => 'Enter either left or right.',
         '#required' => TRUE,
     );
     $form['phrase'] = array(
         '#title' => 'Phrase',
         '#type' => 'textfield',
         '#description' => 'Please enter a phrase that you wish to translate. Numbers and punctuation will not change.',
         '#required' => TRUE,
     );
     $form['submit'] = array(
         '#type' => 'submit',
         '#value' => 'Submit',
     );
     return $form;
 }

//Validations
 function shift_cipher_form_validate($form, &$form_state) {
     $shift_direction = strtolower($form_state['values']['shift_direction']);
     if ($shift_direction !== 'left' && $shift_direction !== 'right') {
         form_set_error('shift_direction', 'Please enter either left or right as a shift direction.');
     }
 }

 function shift_cipher_form_submit($form, &$form_state) {
     $output = '';
     $shift_value = $form_state['values']['shift_value'];
     $shift_direction = strtolower($form_state['values']['shift_direction']);
     $phrase = $form_state['values']['phrase'];
     $phrase = str_split($phrase);
     foreach ($phrase as $letter) {
         $letter = strtolower($letter);
         if (preg_match("/[a-z]/", $letter) && $shift_direction === 'left') {
             $ascii = ord($letter) - $shift_value;
             if ($ascii > 96) {
                 $letter = chr($ascii);
                 $output .= $letter;
            } else {
                $difference = 97 - $ascii;
                $ascii = 123 - $difference;
                $letter = chr($ascii);
                $output .= $letter;
            }
         }
         else if (preg_match("/[a-z]/", $letter)) {
             $ascii = ord($letter) + $shift_value;
             if ($ascii < 123) {
                 $letter = chr($ascii);
                 $output .= $letter;
            } else if ($ascii >= 123){
                $difference = $ascii - 122;
                $ascii = 96 + ($ascii - 122);
                $letter = chr($ascii);
                $output .= $letter;
            }
        }
         else {
             $output .= $letter;
         }
     }
     $_SESSION['results'] = $output;
     $form_state['redirect'] = 'shift_cipher_results_page';
 }

 function shift_cipher_results() {
     return $_SESSION['results'];
 }
